"""create prices table

Revision ID: 3daaa2358410
Revises: 
Create Date: 2026-02-08 15:17:10.356495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daaa2358410'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ts', name='uq_prices_ticker_ts')
    )
    op.create_index('ix_prices_ticker_ts', 'prices', ['ticker', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker_ts', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
